---
apiVersion: v1
kind: Service
metadata:
  name: app-demo
spec:
  selector:
    app: app-demo
  type: ClusterIP
  ports:
  - name: app-demo-port
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-demo-configmap
data:
  node.env: production
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
  ui.properties: |
    color.good=purple
    color.bad=yellow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
spec:
  selector:
    matchLabels:
      app: app-demo
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - image: micjoycexu90/app-demo:v0.0.1
        imagePullPolicy: IfNotPresent
        name: app-demo
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "1000m"
            memory: "1000M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-demo-configmap
              key: node.env
        ports:
        - containerPort: 3000
          name: app-demo
        volumeMounts:
          - name: app-demo-volume
            mountPath: /etc/config # full path: /etc/config/app.properties
      volumes:
        - name: app-demo-volume
          configMap:
            name: app-demo-configmap
            items:
              - key: game.properties
                path: app.properties
      restartPolicy: Always