apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
spec:
  selector:
    matchLabels:
      app: app-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - image: micjoycexu90/app-demo:v0.0.1
        imagePullPolicy: IfNotPresent
        name: app-demo
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "1000m"
            memory: "1000M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: NODE_ENV
          value: production       
        ports:
        - containerPort: 3000
          name: app-demo
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always