apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-demo
  labels:
    name: app-demo
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: app-demo
    spec:
      containers:
      - image: ipedrazas/docmock
        name: app-demo
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "200m"
            memory: "300M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: ENVVARNAME
          value: ENVVARVALUE       
        ports:
        - containerPort: 5000
          name: app-demo
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always